# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
