# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='passwd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
