# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodSite', '0002_auto_20170225_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentorders',
            old_name='rest_id',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='currentorders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='fooditems',
            old_name='rest_id',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='rest_id',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='rest_id',
            new_name='rest',
        ),
    ]
