# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodSite', '0004_remove_fooditems_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='passwd',
        ),
    ]
