# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodSite', '0005_auto_20170225_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentorders',
            name='address',
        ),
    ]
