# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodSite', '0006_remove_currentorders_address'),
        ('foodSite', '0005_auto_20170225_2345'),
    ]

    operations = [
    ]
